In [2]:
from tensorflow.keras.preprocessing.text import one_hot

g:\deep learning project\venv\Lib\site-packages\PIL\Image.py:116: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 10.4.0
Pillow version: 12.1.1
  warnings.warn(str(v), RuntimeWarning)


g:\deep learning project\venv\Lib\site-packages\PIL\Image.py:116: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 10.4.0
Pillow version: 12.1.1
  warnings.warn(str(v), RuntimeWarning)


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8781, 7452, 1518, 7464],
 [8781, 7452, 1518, 517],
 [8781, 1618, 1518, 6191],
 [7846, 6962, 8533, 2156, 5874],
 [7846, 6962, 8533, 2156, 3777],
 [5666, 8781, 7943, 1518, 7669],
 [4764, 7219, 725, 2156]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8781 7452 1518 7464]
 [   0    0    0    0 8781 7452 1518  517]
 [   0    0    0    0 8781 1618 1518 6191]
 [   0    0    0 7846 6962 8533 2156 5874]
 [   0    0    0 7846 6962 8533 2156 3777]
 [   0    0    0 5666 8781 7943 1518 7669]
 [   0    0    0    0 4764 7219  725 2156]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 133ms/step


array([[[ 0.04411915,  0.02826158, -0.02001188, -0.00175589,
         -0.03215927,  0.00606519, -0.04701749, -0.04157092,
          0.00330826, -0.04564345],
        [ 0.04411915,  0.02826158, -0.02001188, -0.00175589,
         -0.03215927,  0.00606519, -0.04701749, -0.04157092,
          0.00330826, -0.04564345],
        [ 0.04411915,  0.02826158, -0.02001188, -0.00175589,
         -0.03215927,  0.00606519, -0.04701749, -0.04157092,
          0.00330826, -0.04564345],
        [ 0.04411915,  0.02826158, -0.02001188, -0.00175589,
         -0.03215927,  0.00606519, -0.04701749, -0.04157092,
          0.00330826, -0.04564345],
        [-0.0321845 , -0.04902325, -0.01395845,  0.02557773,
          0.02170321, -0.04447651, -0.03228966,  0.0185851 ,
          0.02607786, -0.03943174],
        [-0.02953242,  0.04870788, -0.03888496, -0.02850379,
          0.01522355,  0.01161209,  0.03427246, -0.0321097 ,
          0.02461607, -0.01209153],
        [-0.04046148, -0.02063332, -0.04956331, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8781, 7452, 1518, 7464])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[ 0.04411915,  0.02826158, -0.02001188, -0.00175589, -0.03215927,
         0.00606519, -0.04701749, -0.04157092,  0.00330826, -0.04564345],
       [ 0.04411915,  0.02826158, -0.02001188, -0.00175589, -0.03215927,
         0.00606519, -0.04701749, -0.04157092,  0.00330826, -0.04564345],
       [ 0.04411915,  0.02826158, -0.02001188, -0.00175589, -0.03215927,
         0.00606519, -0.04701749, -0.04157092,  0.00330826, -0.04564345],
       [ 0.04411915,  0.02826158, -0.02001188, -0.00175589, -0.03215927,
         0.00606519, -0.04701749, -0.04157092,  0.00330826, -0.04564345],
       [-0.0321845 , -0.04902325, -0.01395845,  0.02557773,  0.02170321,
        -0.04447651, -0.03228966,  0.0185851 ,  0.02607786, -0.03943174],
       [-0.02953242,  0.04870788, -0.03888496, -0.02850379,  0.01522355,
         0.01161209,  0.03427246, -0.0321097 ,  0.02461607, -0.01209153],
       [-0.04046148, -0.02063332, -0.04956331, -0.02566177,  0.03355403,
        -0.00837004, -0.00505822,  0.04374972